<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<applicationModel>
    <name>Application Model</name>
    <className>AODWeb</className>
    <objects>
        <object type="EditField" technology="Web">
            <name>ContactUsSubject</name>
            <codeName>ContactUsSubject</codeName>
            <identification>
                <properties>
                    <property name="Name" type="string" isRegExp="false">WebEdit</property>
                    <property name="Type" type="string" isRegExp="false">textarea</property>
                    <property name="TagName" type="string" isRegExp="false">TEXTAREA</property>
                </properties>
            </identification>
        </object>
    </objects>
</applicationModel>
